services:
  - type: web
    name: dota-drafts
    runtime: node
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SCRAPING_INTERVAL
        value: "30000"
