services:
  - type: web
    name: dota-drafts
    runtime: node
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend && npm install --prefix backend
    startCommand: node backend/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SCRAPING_INTERVAL
        value: "30000"
