services:
  - type: web
    name: dota-drafts
    runtime: node
    rootDir: backend
    buildCommand: cd ../frontend && npm install && npm run build
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SCRAPING_INTERVAL
        value: 30000
