const HERO_ICONS = {
  'anti-mage': '🗡️', 'axe': '🪓', 'bane': '👁️', 'bloodseeker': '🩸',
  'crystal-maiden': '❄️', 'drow-ranger': '🏹', 'earthshaker': '🌋',
  'juggernaut': '⚔️', 'mirana': '🌙', 'shadow-fiend': '👻',
  'morphling': '💧', 'phantom-lancer': '🗡️', 'puck': '🧚',
  'pudge': '🪝', 'razor': '⚡', 'sand-king': '🐜', 'storm-spirit': '🌪️',
  'tinker': '🔧', 'zeus': '⚡', 'kunkka': '⚓', 'lina': '🔥',
  'lion': '🦁', 'shadow-shaman': '🦅', 'slardar': '🦈', 'tidehunter': '🐋',
  'witch-doctor': '🧙', 'lich': '❄️', 'riki': '🗡️', 'enigma': '🌀',
  'tinker': '🔧', 'sniper': '🎯', 'necrophos': '💀', 'warlock': '📖',
  'beastmaster': '🐗', 'queen-of-pain': '👑', 'venomancer': '🐍',
  'faceless-void': '👤', 'skeleton-king': '💀', 'death-prophet': '👻',
  'phantom-assassin': '🗡️', 'pugna': '💀', 'templar-assassin': '🗡️',
  'viper': '🐍', 'luna': '🌙', 'dragon-knight': '🐉', 'dazzle': '✨',
  'rattletrap': '⚙️', 'leshrac': '⚡', 'furion': '🌿', 'chaos-knight': '🐴',
  'rubick': '🧙', 'treant': '🌳', 'ogre-magi': '👹', 'invoker': '🌟',
  'silencer': '🔇', 'obsidian-destroyer': '🌑', 'lycan': '🐺',
  'brewmaster': '🍺', 'shadow-demon': '😈', 'lone-druid': '🐻',
  'chaos-knight': '🐴', 'spirit-breaker': '🐃', 'keeper-of-the-light': '💡',
  'wisp': '⚪', 'centaur': '🐎', 'magnus': '🦏', 'timbersaw': '🪚',
  'bristleback': '🦔', 'tusk': '❄️', 'skywrath-mage': '🦅',
  'abyssal-underlord': '🕳️', 'elder-titan': '🗿', 'techies': '💣',
  'legion-commander': '⚔️', 'ember-spirit': '🔥', 'earth-spirit': '🪨',
  'phoenix': '🔥', 'terrorblade': '😈', 'oracle': '🔮',
  'arc-warden': '⚡', 'monkey-king': '🐒', 'pangolier': '🐊',
  'dark-willow': '🌿', 'night-stalker': '🦇', 'doom': '😈',
  'io': '⚪', 'gyrocopter': '🚁', 'alchemist': '⚗️', 'underlord': '🕳️',
  'windranger': '🏹', 'grimstroke': '🖌️', 'hoodwink': '🐿️',
  'void-spirit': '👤', 'mars': '⚔️', 'snapfire': '🐊',
  'grimstroke': '🖌️', 'dawnbreaker': '☀️', 'marci': '💪',
  'primal-beast': '🐾', 'muerta': '💀', 'kez': '🗡️',
  'generic-str': '🛡️', 'generic-agi': '⚔️', 'generic-int': '✨',
  'lifestealer': '🧛', 'broodmother': '🕷️', 'naga-siren': '🧜',
  'visage': '🦇', 'meepo': '⛏️', 'batrider': '🦇',
  'ancient-apparition': '❄️', 'outworld-destroyer': '🌑',
  'abyssal-underlord': '🕳️', 'shadow-fiend': '👻', 'naga-siren': '🧜',
}

const heroes = {}

const heroList = [
  [1, 'anti-mage', 'Anti-Mage', 'agi'],
  [2, 'axe', 'Axe', 'str'],
  [3, 'bane', 'Bane', 'int'],
  [4, 'bloodseeker', 'Bloodseeker', 'agi'],
  [5, 'crystal-maiden', 'Crystal Maiden', 'int'],
  [6, 'drow-ranger', 'Drow Ranger', 'agi'],
  [7, 'earthshaker', 'Earthshaker', 'str'],
  [8, 'juggernaut', 'Juggernaut', 'agi'],
  [9, 'mirana', 'Mirana', 'agi'],
  [10, 'morphling', 'Morphling', 'agi'],
  [11, 'shadow-fiend', 'Shadow Fiend', 'agi'],
  [12, 'phantom-lancer', 'Phantom Lancer', 'agi'],
  [13, 'puck', 'Puck', 'int'],
  [14, 'pudge', 'Pudge', 'str'],
  [15, 'razor', 'Razor', 'agi'],
  [16, 'sand-king', 'Sand King', 'str'],
  [17, 'storm-spirit', 'Storm Spirit', 'int'],
  [18, 'tinker', 'Tinker', 'int'],
  [19, 'zeus', 'Zeus', 'int'],
  [20, 'kunkka', 'Kunkka', 'str'],
  [21, 'lina', 'Lina', 'int'],
  [22, 'lion', 'Lion', 'int'],
  [23, 'shadow-shaman', 'Shadow Shaman', 'int'],
  [24, 'slardar', 'Slardar', 'str'],
  [25, 'tidehunter', 'Tidehunter', 'str'],
  [26, 'witch-doctor', 'Witch Doctor', 'int'],
  [27, 'lich', 'Lich', 'int'],
  [28, 'riki', 'Riki', 'agi'],
  [29, 'enigma', 'Enigma', 'int'],
  [30, 'tinker', 'Tinker', 'int'],
  [31, 'sniper', 'Sniper', 'agi'],
  [32, 'necrophos', 'Necrophos', 'int'],
  [33, 'warlock', 'Warlock', 'int'],
  [34, 'beastmaster', 'Beastmaster', 'str'],
  [35, 'queen-of-pain', 'Queen of Pain', 'int'],
  [36, 'venomancer', 'Venomancer', 'agi'],
  [37, 'faceless-void', 'Faceless Void', 'agi'],
  [38, 'skeleton-king', 'Wraith King', 'str'],
  [39, 'death-prophet', 'Death Prophet', 'int'],
  [40, 'phantom-assassin', 'Phantom Assassin', 'agi'],
  [41, 'pugna', 'Pugna', 'int'],
  [42, 'templar-assassin', 'Templar Assassin', 'agi'],
  [43, 'viper', 'Viper', 'agi'],
  [44, 'luna', 'Luna', 'agi'],
  [45, 'dragon-knight', 'Dragon Knight', 'str'],
  [46, 'dazzle', 'Dazzle', 'int'],
  [47, 'rattletrap', 'Clockwerk', 'str'],
  [48, 'leshrac', 'Leshrac', 'int'],
  [49, "furion", "Nature's Prophet", 'int'],
  [50, 'chaos-knight', 'Chaos Knight', 'str'],
  [51, 'rubick', 'Rubick', 'int'],
  [52, 'treant', 'Treant Protector', 'str'],
  [53, 'ogre-magi', 'Ogre Magi', 'int'],
  [54, 'invoker', 'Invoker', 'int'],
  [55, 'silencer', 'Silencer', 'int'],
  [56, 'outworld-destroyer', 'Outworld Destroyer', 'int'],
  [57, 'lycan', 'Lycan', 'str'],
  [58, 'brewmaster', 'Brewmaster', 'str'],
  [59, 'shadow-demon', 'Shadow Demon', 'int'],
  [60, 'lone-druid', 'Lone Druid', 'agi'],
  [61, 'chaos-knight', 'Chaos Knight', 'str'],
  [62, 'spirit-breaker', 'Spirit Breaker', 'str'],
  [63, 'keeper-of-the-light', 'Keeper of the Light', 'int'],
  [64, 'io', 'Io', 'str'],
  [65, 'visage', 'Visage', 'int'],
  [66, 'slark', 'Slark', 'agi'],
  [67, 'medusa', 'Medusa', 'agi'],
  [68, 'troll-warlord', 'Troll Warlord', 'agi'],
  [69, 'centaur', 'Centaur Warrunner', 'str'],
  [70, 'magnus', 'Magnus', 'str'],
  [71, 'axe', 'Axe', 'str'],
  [72, 'huskar', 'Huskar', 'str'],
  [73, 'night-stalker', 'Night Stalker', 'str'],
  [74, 'broodmother', 'Broodmother', 'agi'],
  [75, 'bounty-hunter', 'Bounty Hunter', 'agi'],
  [76, 'weaver', 'Weaver', 'agi'],
  [77, 'jakiro', 'Jakiro', 'int'],
  [78, 'batrider', 'Batrider', 'int'],
  [79, 'chen', 'Chen', 'int'],
  [80, 'spectre', 'Spectre', 'agi'],
  [81, 'doom', 'Doom', 'str'],
  [82, 'ancient-apparition', 'Ancient Apparition', 'int'],
  [83, 'ursa', 'Ursa', 'agi'],
  [84, 'spirit-breaker', 'Spirit Breaker', 'str'],
  [85, 'gyrocopter', 'Gyrocopter', 'agi'],
  [86, 'alchemist', 'Alchemist', 'str'],
  [87, 'invoker', 'Invoker', 'int'],
  [88, 'shadow-shaman', 'Shadow Shaman', 'int'],
  [89, 'naga-siren', 'Naga Siren', 'agi'],
  [90, 'meepo', 'Meepo', 'agi'],
  [91, 'nyx-assassin', 'Nyx Assassin', 'agi'],
  [92, 'io', 'Io', 'str'],
  [93, 'windranger', 'Windranger', 'int'],
  [94, 'phoenix', 'Phoenix', 'str'],
  [95, 'terrorblade', 'Terrorblade', 'agi'],
  [96, 'oracle', 'Oracle', 'int'],
  [97, 'abaddon', 'Abaddon', 'str'],
  [98, 'elder-titan', 'Elder Titan', 'str'],
  [99, 'legion-commander', 'Legion Commander', 'str'],
  [100, 'techies', 'Techies', 'agi'],
  [101, 'ember-spirit', 'Ember Spirit', 'agi'],
  [102, 'earth-spirit', 'Earth Spirit', 'str'],
  [103, 'abyssal-underlord', 'Underlord', 'str'],
  [104, 'terrorblade', 'Terrorblade', 'agi'],
  [105, 'phoenix', 'Phoenix', 'str'],
  [106, 'oracle', 'Oracle', 'int'],
  [107, 'winter-wyvern', 'Winter Wyvern', 'int'],
  [108, 'arc-warden', 'Arc Warden', 'agi'],
  [109, 'monkey-king', 'Monkey King', 'agi'],
  [110, 'pangolier', 'Pangolier', 'agi'],
  [111, 'dark-willow', 'Dark Willow', 'int'],
  [112, 'pugna', 'Pugna', 'int'],
  [113, 'grimstroke', 'Grimstroke', 'int'],
  [114, 'mars', 'Mars', 'str'],
  [115, 'snapfire', 'Snapfire', 'agi'],
  [116, 'void-spirit', 'Void Spirit', 'int'],
  [117, 'hoodwink', 'Hoodwink', 'agi'],
  [118, 'dawnbreaker', 'Dawnbreaker', 'str'],
  [119, 'marci', 'Marci', 'agi'],
  [120, 'primal-beast', 'Primal Beast', 'str'],
  [121, 'muerta', 'Muerta', 'agi'],
  [122, 'kez', 'Kez', 'agi'],
  [123, 'beastmaster', 'Beastmaster', 'str'],
  [124, 'brewmaster', 'Brewmaster', 'str'],
  [125, 'chaos-knight', 'Chaos Knight', 'str'],
  [126, 'keeper-of-the-light', 'Keeper of the Light', 'int'],
  [127, 'lycan', 'Lycan', 'str'],
  [128, 'oracle', 'Oracle', 'int'],
  [129, 'shadow-demon', 'Shadow Demon', 'int'],
  [130, 'abyssal-underlord', 'Underlord', 'str'],
  [131, 'lone-druid', 'Lone Druid', 'agi'],
  [132, 'naga-siren', 'Naga Siren', 'agi'],
  [133, 'io', 'Io', 'str'],
  [134, 'visage', 'Visage', 'int'],
  [135, 'spirit-breaker', 'Spirit Breaker', 'str'],
  [136, 'troll-warlord', 'Troll Warlord', 'agi'],
  [137, 'tusk', 'Tusk', 'str'],
  [138, 'skywrath-mage', 'Skywrath Mage', 'int'],
  [139, 'centaur', 'Centaur Warrunner', 'str'],
  [140, 'treant', 'Treant Protector', 'str'],
  [141, 'ogre-magi', 'Ogre Magi', 'int'],
  [142, 'rattletrap', 'Clockwerk', 'str'],
  [143, 'furion', "Nature's Prophet", 'int'],
  [144, 'keeper-of-the-light', 'Keeper of the Light', 'int'],
  [145, 'lich', 'Lich', 'int'],
  [146, 'silencer', 'Silencer', 'int'],
  [147, 'outworld-destroyer', 'Outworld Destroyer', 'int'],
  [148, 'warlock', 'Warlock', 'int'],
  [149, 'death-prophet', 'Death Prophet', 'int'],
  [150, 'venomancer', 'Venomancer', 'agi'],
  [151, 'witch-doctor', 'Witch Doctor', 'int'],
  [152, 'ancient-apparition', 'Ancient Apparition', 'int'],
  [153, 'shadow-shaman', 'Shadow Shaman', 'int'],
  [154, 'enigma', 'Enigma', 'int'],
  [155, 'doom', 'Doom', 'str'],
  [156, 'batrider', 'Batrider', 'int'],
  [157, 'broodmother', 'Broodmother', 'agi'],
  [158, 'chen', 'Chen', 'int'],
  [159, 'bane', 'Bane', 'int'],
  [160, 'slardar', 'Slardar', 'str'],
  [161, 'tidehunter', 'Tidehunter', 'str'],
  [162, 'zeus', 'Zeus', 'int'],
  [163, 'storm-spirit', 'Storm Spirit', 'int'],
  [164, 'kunkka', 'Kunkka', 'str'],
  [165, 'sand-king', 'Sand King', 'str'],
  [166, 'razor', 'Razor', 'agi'],
  [167, 'spectre', 'Spectre', 'agi'],
  [168, 'ursa', 'Ursa', 'agi'],
  [169, 'faceless-void', 'Faceless Void', 'agi'],
  [170, 'necrophos', 'Necrophos', 'int'],
  [171, 'skeleton-king', 'Wraith King', 'str'],
  [172, 'juggernaut', 'Juggernaut', 'agi'],
  [173, 'earthshaker', 'Earthshaker', 'str'],
  [174, 'crystal-maiden', 'Crystal Maiden', 'int'],
  [175, 'anti-mage', 'Anti-Mage', 'agi'],
  [176, 'bloodseeker', 'Bloodseeker', 'agi'],
  [177, 'lion', 'Lion', 'int'],
  [178, 'queen-of-pain', 'Queen of Pain', 'int'],
  [179, 'dazzle', 'Dazzle', 'int'],
  [180, 'pugna', 'Pugna', 'int'],
  [181, 'morphling', 'Morphling', 'agi'],
  [182, 'lina', 'Lina', 'int'],
  [183, 'phantom-assassin', 'Phantom Assassin', 'agi'],
  [184, 'venomancer', 'Venomancer', 'agi'],
  [185, 'sniper', 'Sniper', 'agi'],
  [186, 'invoker', 'Invoker', 'int'],
  [187, 'windranger', 'Windranger', 'int'],
  [188, 'pudge', 'Pudge', 'str'],
  [189, 'shadow-fiend', 'Shadow Fiend', 'agi'],
  [190, 'drow-ranger', 'Drow Ranger', 'agi'],
  [191, 'phantom-lancer', 'Phantom Lancer', 'agi'],
  [192, 'dragon-knight', 'Dragon Knight', 'str'],
  [193, 'luna', 'Luna', 'agi'],
  [194, 'medusa', 'Medusa', 'agi'],
  [195, 'viper', 'Viper', 'agi'],
  [196, 'templar-assassin', 'Templar Assassin', 'agi'],
  [197, 'gyrocopter', 'Gyrocopter', 'agi'],
  [198, 'alchemist', 'Alchemist', 'str'],
  [199, 'leshrac', 'Leshrac', 'int'],
  [200, 'tinker', 'Tinker', 'int'],
  [201, 'huskar', 'Huskar', 'str'],
  [202, 'night-stalker', 'Night Stalker', 'str'],
  [203, 'puck', 'Puck', 'int'],
  [204, 'magnus', 'Magnus', 'str'],
  [205, 'weaver', 'Weaver', 'agi'],
  [206, 'lifestealer', 'Lifestealer', 'str'],
  [207, 'bounty-hunter', 'Bounty Hunter', 'agi'],
  [208, 'jakiro', 'Jakiro', 'int'],
  [209, 'slark', 'Slark', 'agi'],
  [210, 'riki', 'Riki', 'agi'],
  [211, 'nyx-assassin', 'Nyx Assassin', 'agi'],
  [212, 'abaddon', 'Abaddon', 'str'],
  [213, 'arc-warden', 'Arc Warden', 'agi'],
  [214, 'terrorblade', 'Terrorblade', 'agi'],
  [215, 'brewmaster', 'Brewmaster', 'str'],
  [216, 'spirit-breaker', 'Spirit Breaker', 'str'],
  [217, 'meepo', 'Meepo', 'agi'],
  [218, 'io', 'Io', 'str'],
  [219, 'keeper-of-the-light', 'Keeper of the Light', 'int'],
  [220, 'winter-wyvern', 'Winter Wyvern', 'int'],
  [221, 'treant', 'Treant Protector', 'str'],
  [222, 'lone-druid', 'Lone Druid', 'agi'],
  [223, 'naga-siren', 'Naga Siren', 'agi'],
  [224, 'visage', 'Visage', 'int'],
  [225, 'lycan', 'Lycan', 'str'],
  [226, 'shadow-demon', 'Shadow Demon', 'int'],
  [227, 'ogre-magi', 'Ogre Magi', 'int'],
  [228, 'centaur', 'Centaur Warrunner', 'str'],
  [229, 'rattletrap', 'Clockwerk', 'str'],
  [230, 'furion', "Nature's Prophet", 'int'],
  [231, 'lich', 'Lich', 'int'],
  [232, 'silencer', 'Silencer', 'int'],
  [233, 'outworld-destroyer', 'Outworld Destroyer', 'int'],
  [234, 'tidehunter', 'Tidehunter', 'str'],
  [235, 'warlock', 'Warlock', 'int'],
  [236, 'shadow-shaman', 'Shadow Shaman', 'int'],
  [237, 'enigma', 'Enigma', 'int'],
  [238, 'doom', 'Doom', 'str'],
  [239, 'batrider', 'Batrider', 'int'],
  [240, 'broodmother', 'Broodmother', 'agi'],
  [241, 'chen', 'Chen', 'int'],
  [242, 'bane', 'Bane', 'int'],
  [243, 'slardar', 'Slardar', 'str'],
  [244, 'zeus', 'Zeus', 'int'],
  [245, 'storm-spirit', 'Storm Spirit', 'int'],
  [246, 'kunkka', 'Kunkka', 'str'],
  [247, 'sand-king', 'Sand King', 'str'],
  [248, 'razor', 'Razor', 'agi'],
  [249, 'spectre', 'Spectre', 'agi'],
  [250, 'ursa', 'Ursa', 'agi'],
]

heroList.forEach(([id, slug, name, attr]) => {
  if (!heroes[name]) {
    heroes[name] = {
      id,
      name,
      slug,
      attribute: attr,
      icon: HERO_ICONS[slug] || '❓',
      image: `https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/${slug}.png`
    }
  }
})

heroes['Unknown'] = { id: 0, name: 'Unknown', slug: 'unknown', attribute: 'str', icon: '❓', image: null }

export { heroes }

export function getHeroByName(name) {
  return heroes[name] || heroes['Unknown']
}

export function getHeroImage(name) {
  const hero = heroes[name]
  return hero?.image || null
}

export function getHeroBySlug(slug) {
  return Object.values(heroes).find(h => h.slug === slug) || heroes['Unknown']
}
