const HERO_ICONS = {
  'anti-mage': '🗡️', 'axe': '🪓', 'bane': '👁️', 'bloodseeker': '🩸',
  'crystal-maiden': '❄️', 'drow-ranger': '🏹', 'earthshaker': '🌋',
  'juggernaut': '⚔️', 'mirana': '🌙', 'shadow-fiend': '👻',
  'morphling': '💧', 'phantom-lancer': '🗡️', 'puck': '🧚',
  'pudge': '🪝', 'razor': '⚡', 'sand-king': '🐜', 'storm-spirit': '🌪️',
  'tinker': '🔧', 'zeus': '⚡', 'kunkka': '⚓', 'lina': '🔥',
  'lion': '🦁', 'shadow-shaman': '🦅', 'slardar': '🦈', 'tidehunter': '🐋',
  'witch-doctor': '🧙', 'lich': '❄️', 'riki': '🗡️', 'enigma': '🌀',
  'sniper': '🎯', 'necrophos': '💀', 'warlock': '📖',
  'beastmaster': '🐗', 'queen-of-pain': '👑', 'venomancer': '🐍',
  'faceless-void': '👤', 'skeleton-king': '💀', 'death-prophet': '👻',
  'phantom-assassin': '🗡️', 'pugna': '💀', 'templar-assassin': '🗡️',
  'viper': '🐍', 'luna': '🌙', 'dragon-knight': '🐉', 'dazzle': '✨',
  'rattletrap': '⚙️', 'leshrac': '⚡', 'furion': '🌿', 'chaos-knight': '🐴',
  'rubick': '🧙', 'treant': '🌳', 'ogre-magi': '👹', 'invoker': '🌟',
  'silencer': '🔇', 'obsidian-destroyer': '🌑', 'lycan': '🐺',
  'brewmaster': '🍺', 'shadow-demon': '😈', 'lone-druid': '🐻',
  'spirit-breaker': '🐃', 'keeper-of-the-light': '💡',
  'wisp': '⚪', 'centaur': '🐎', 'magnus': '🦏', 'timbersaw': '🪚',
  'bristleback': '🦔', 'tusk': '❄️', 'skywrath-mage': '🦅',
  'abyssal-underlord': '🕳️', 'elder-titan': '🗿', 'techies': '💣',
  'legion-commander': '⚔️', 'ember-spirit': '🔥', 'earth-spirit': '🪨',
  'phoenix': '🔥', 'terrorblade': '😈', 'oracle': '🔮',
  'arc-warden': '⚡', 'monkey-king': '🐒', 'pangolier': '🐊',
  'dark-willow': '🌿', 'night-stalker': '🦇', 'doom': '😈',
  'io': '⚪', 'gyrocopter': '🚁', 'alchemist': '⚗️', 'underlord': '🕳️',
  'windranger': '🏹', 'grimstroke': '🖌️', 'hoodwink': '🐿️',
  'void-spirit': '👤', 'mars': '⚔️', 'snapfire': '🐊',
  'dawnbreaker': '☀️', 'marci': '💪',
  'primal-beast': '🐾', 'muerta': '💀', 'kez': '🗡️',
  'generic-str': '🛡️', 'generic-agi': '⚔️', 'generic-int': '✨',
  'lifestealer': '🧛', 'broodmother': '🕷️', 'naga-siren': '🧜',
  'visage': '🦇', 'meepo': '⛏️', 'batrider': '🦇',
  'ancient-apparition': '❄️', 'outworld-destroyer': '🌑',
}

const STEAM_SLUGS = {
  'Anti-Mage': 'antimage',
  'Axe': 'axe',
  'Bane': 'bane',
  'Bloodseeker': 'bloodseeker',
  'Crystal Maiden': 'crystal_maiden',
  'Drow Ranger': 'drow_ranger',
  'Earthshaker': 'earthshaker',
  'Juggernaut': 'juggernaut',
  'Mirana': 'mirana',
  'Morphling': 'morphling',
  'Shadow Fiend': 'nevermore',
  'Phantom Lancer': 'phantom_lancer',
  'Puck': 'puck',
  'Pudge': 'pudge',
  'Razor': 'razor',
  'Sand King': 'sand_king',
  'Storm Spirit': 'storm_spirit',
  'Tinker': 'tinker',
  'Zeus': 'zuus',
  'Kunkka': 'kunkka',
  'Lina': 'lina',
  'Lion': 'lion',
  'Shadow Shaman': 'shadow_shaman',
  'Slardar': 'slardar',
  'Tidehunter': 'tidehunter',
  'Witch Doctor': 'witch_doctor',
  'Lich': 'lich',
  'Riki': 'riki',
  'Enigma': 'enigma',
  'Sniper': 'sniper',
  'Necrophos': 'necrolyte',
  'Warlock': 'warlock',
  'Beastmaster': 'beastmaster',
  'Queen of Pain': 'queenofpain',
  'Venomancer': 'venomancer',
  'Faceless Void': 'faceless_void',
  'Wraith King': 'skeleton_king',
  'Death Prophet': 'death_prophet',
  'Phantom Assassin': 'phantom_assassin',
  'Pugna': 'pugna',
  'Templar Assassin': 'templar_assassin',
  'Viper': 'viper',
  'Luna': 'luna',
  'Dragon Knight': 'dragon_knight',
  'Dazzle': 'dazzle',
  'Clockwerk': 'rattletrap',
  'Leshrac': 'leshrac',
  "Nature's Prophet": 'furion',
  'Chaos Knight': 'chaos_knight',
  'Rubick': 'rubick',
  'Treant Protector': 'treant',
  'Ogre Magi': 'ogre_magi',
  'Invoker': 'invoker',
  'Silencer': 'silencer',
  'Outworld Destroyer': 'obsidian_destroyer',
  'Lycan': 'lycan',
  'Brewmaster': 'brewmaster',
  'Shadow Demon': 'shadow_demon',
  'Lone Druid': 'lone_druid',
  'Spirit Breaker': 'spirit_breaker',
  'Keeper of the Light': 'keeper_of_the_light',
  'Io': 'wisp',
  'Centaur Warrunner': 'centaur',
  'Magnus': 'magnus',
  'Timbersaw': 'shredder',
  'Bristleback': 'bristleback',
  'Tusk': 'tusk',
  'Skywrath Mage': 'skywrath_mage',
  'Underlord': 'abyssal_underlord',
  'Elder Titan': 'elder_titan',
  'Techies': 'techies',
  'Legion Commander': 'legion_commander',
  'Ember Spirit': 'ember_spirit',
  'Earth Spirit': 'earth_spirit',
  'Phoenix': 'phoenix',
  'Terrorblade': 'terrorblade',
  'Oracle': 'oracle',
  'Arc Warden': 'arc_warden',
  'Monkey King': 'monkey_king',
  'Pangolier': 'pangolier',
  'Dark Willow': 'dark_willow',
  'Night Stalker': 'night_stalker',
  'Doom': 'doom_bringer',
  'Gyrocopter': 'gyrocopter',
  'Alchemist': 'alchemist',
  'Underlord': 'abyssal_underlord',
  'Windranger': 'windrunner',
  'Grimstroke': 'grimstroke',
  'Hoodwink': 'hoodwink',
  'Void Spirit': 'void_spirit',
  'Mars': 'mars',
  'Snapfire': 'snapfire',
  'Dawnbreaker': 'dawnbreaker',
  'Marci': 'marci',
  'Primal Beast': 'primal_beast',
  'Muerta': 'muerta',
  'Kez': 'kez',
  'Lifestealer': 'life_stealer',
  'Broodmother': 'broodmother',
  'Naga Siren': 'naga_siren',
  'Visage': 'visage',
  'Meepo': 'meepo',
  'Batrider': 'batrider',
  'Ancient Apparition': 'ancient_apparition',
  'Pangolier': 'pangolier',
  'Underlord': 'abyssal_underlord',
}

const heroes = {}

const heroList = [
  [1, 'anti-mage', 'Anti-Mage', 'agi'],
  [2, 'axe', 'Axe', 'str'],
  [3, 'bane', 'Bane', 'int'],
  [4, 'bloodseeker', 'Bloodseeker', 'agi'],
  [5, 'crystal-maiden', 'Crystal Maiden', 'int'],
  [6, 'drow-ranger', 'Drow Ranger', 'agi'],
  [7, 'earthshaker', 'Earthshaker', 'str'],
  [8, 'juggernaut', 'Juggernaut', 'agi'],
  [9, 'mirana', 'Mirana', 'agi'],
  [10, 'morphling', 'Morphling', 'agi'],
  [11, 'shadow-fiend', 'Shadow Fiend', 'agi'],
  [12, 'phantom-lancer', 'Phantom Lancer', 'agi'],
  [13, 'puck', 'Puck', 'int'],
  [14, 'pudge', 'Pudge', 'str'],
  [15, 'razor', 'Razor', 'agi'],
  [16, 'sand-king', 'Sand King', 'str'],
  [17, 'storm-spirit', 'Storm Spirit', 'int'],
  [18, 'tinker', 'Tinker', 'int'],
  [19, 'zeus', 'Zeus', 'int'],
  [20, 'kunkka', 'Kunkka', 'str'],
  [21, 'lina', 'Lina', 'int'],
  [22, 'lion', 'Lion', 'int'],
  [23, 'shadow-shaman', 'Shadow Shaman', 'int'],
  [24, 'slardar', 'Slardar', 'str'],
  [25, 'tidehunter', 'Tidehunter', 'str'],
  [26, 'witch-doctor', 'Witch Doctor', 'int'],
  [27, 'lich', 'Lich', 'int'],
  [28, 'riki', 'Riki', 'agi'],
  [29, 'enigma', 'Enigma', 'int'],
  [31, 'sniper', 'Sniper', 'agi'],
  [32, 'necrophos', 'Necrophos', 'int'],
  [33, 'warlock', 'Warlock', 'int'],
  [34, 'beastmaster', 'Beastmaster', 'str'],
  [35, 'queen-of-pain', 'Queen of Pain', 'int'],
  [36, 'venomancer', 'Venomancer', 'agi'],
  [37, 'faceless-void', 'Faceless Void', 'agi'],
  [38, 'skeleton-king', 'Wraith King', 'str'],
  [39, 'death-prophet', 'Death Prophet', 'int'],
  [40, 'phantom-assassin', 'Phantom Assassin', 'agi'],
  [41, 'pugna', 'Pugna', 'int'],
  [42, 'templar-assassin', 'Templar Assassin', 'agi'],
  [43, 'viper', 'Viper', 'agi'],
  [44, 'luna', 'Luna', 'agi'],
  [45, 'dragon-knight', 'Dragon Knight', 'str'],
  [46, 'dazzle', 'Dazzle', 'int'],
  [47, 'rattletrap', 'Clockwerk', 'str'],
  [48, 'leshrac', 'Leshrac', 'int'],
  [49, "furion", "Nature's Prophet", 'int'],
  [50, 'chaos-knight', 'Chaos Knight', 'str'],
  [51, 'rubick', 'Rubick', 'int'],
  [52, 'treant', 'Treant Protector', 'str'],
  [53, 'ogre-magi', 'Ogre Magi', 'int'],
  [54, 'invoker', 'Invoker', 'int'],
  [55, 'silencer', 'Silencer', 'int'],
  [56, 'outworld-destroyer', 'Outworld Destroyer', 'int'],
  [57, 'lycan', 'Lycan', 'str'],
  [58, 'brewmaster', 'Brewmaster', 'str'],
  [59, 'shadow-demon', 'Shadow Demon', 'int'],
  [60, 'lone-druid', 'Lone Druid', 'agi'],
  [62, 'spirit-breaker', 'Spirit Breaker', 'str'],
  [63, 'keeper-of-the-light', 'Keeper of the Light', 'int'],
  [64, 'io', 'Io', 'str'],
  [65, 'visage', 'Visage', 'int'],
  [66, 'slark', 'Slark', 'agi'],
  [67, 'medusa', 'Medusa', 'agi'],
  [68, 'troll-warlord', 'Troll Warlord', 'agi'],
  [69, 'centaur', 'Centaur Warrunner', 'str'],
  [70, 'magnus', 'Magnus', 'str'],
  [72, 'huskar', 'Huskar', 'str'],
  [73, 'night-stalker', 'Night Stalker', 'str'],
  [74, 'broodmother', 'Broodmother', 'agi'],
  [75, 'bounty-hunter', 'Bounty Hunter', 'agi'],
  [76, 'weaver', 'Weaver', 'agi'],
  [77, 'jakiro', 'Jakiro', 'int'],
  [78, 'batrider', 'Batrider', 'int'],
  [79, 'chen', 'Chen', 'int'],
  [80, 'spectre', 'Spectre', 'agi'],
  [81, 'doom', 'Doom', 'str'],
  [82, 'ancient-apparition', 'Ancient Apparition', 'int'],
  [83, 'ursa', 'Ursa', 'agi'],
  [85, 'gyrocopter', 'Gyrocopter', 'agi'],
  [86, 'alchemist', 'Alchemist', 'str'],
  [89, 'naga-siren', 'Naga Siren', 'agi'],
  [90, 'meepo', 'Meepo', 'agi'],
  [91, 'nyx-assassin', 'Nyx Assassin', 'agi'],
  [93, 'windranger', 'Windranger', 'int'],
  [94, 'phoenix', 'Phoenix', 'str'],
  [95, 'terrorblade', 'Terrorblade', 'agi'],
  [96, 'oracle', 'Oracle', 'int'],
  [97, 'abaddon', 'Abaddon', 'str'],
  [98, 'elder-titan', 'Elder Titan', 'str'],
  [99, 'legion-commander', 'Legion Commander', 'str'],
  [100, 'techies', 'Techies', 'agi'],
  [101, 'ember-spirit', 'Ember Spirit', 'agi'],
  [102, 'earth-spirit', 'Earth Spirit', 'str'],
  [103, 'abyssal-underlord', 'Underlord', 'str'],
  [107, 'winter-wyvern', 'Winter Wyvern', 'int'],
  [108, 'arc-warden', 'Arc Warden', 'agi'],
  [109, 'monkey-king', 'Monkey King', 'agi'],
  [110, 'pangolier', 'Pangolier', 'agi'],
  [111, 'dark-willow', 'Dark Willow', 'int'],
  [113, 'grimstroke', 'Grimstroke', 'int'],
  [114, 'mars', 'Mars', 'str'],
  [115, 'snapfire', 'Snapfire', 'agi'],
  [116, 'void-spirit', 'Void Spirit', 'int'],
  [117, 'hoodwink', 'Hoodwink', 'agi'],
  [118, 'dawnbreaker', 'Dawnbreaker', 'str'],
  [119, 'marci', 'Marci', 'agi'],
  [120, 'primal-beast', 'Primal Beast', 'str'],
  [121, 'muerta', 'Muerta', 'agi'],
  [122, 'kez', 'Kez', 'agi'],
]

heroList.forEach(([id, slug, name, attr]) => {
  if (!heroes[name]) {
    const steamSlug = STEAM_SLUGS[name] || slug.replace(/-/g, '_')
    heroes[name] = {
      id,
      name,
      slug,
      steamSlug,
      attribute: attr,
      icon: HERO_ICONS[slug] || '❓',
      image: `https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/${steamSlug}.png`
    }
  }
})

heroes['Unknown'] = { id: 0, name: 'Unknown', slug: 'unknown', steamSlug: 'unknown', attribute: 'str', icon: '❓', image: null }

export { heroes }

export function getHeroByName(name) {
  return heroes[name] || heroes['Unknown']
}

export function getHeroImage(name) {
  const hero = heroes[name]
  return hero?.image || null
}

export function getHeroBySlug(slug) {
  return Object.values(heroes).find(h => h.slug === slug) || heroes['Unknown']
}
